<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title>Home - Wabi sabi</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="icon" href="assets/img/favicon.svg" type="image/png" sizes="16x16">

    <!-- bootstrape -->
    <link rel="stylesheet" href="assets/styles/bootstrap.min.css">

    <!-- font-awesome -->
    <script src="assets/scripts/font-awesome-5-pro.js"></script>

    <!-- custom -->
    <link rel="stylesheet" href="assets/styles/slick.css">
    <link rel="stylesheet" href="assets/styles/owl_carousel_min.css">
    <link rel="stylesheet" href="assets/styles/owl_theme_default_min.css">
    <link rel="stylesheet" href="assets/styles/fancybox.css">
    <link rel="stylesheet" href="assets/styles/main.css">
    <link rel="stylesheet" href="assets/styles/responsive.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" integrity="sha512-+EoPw+Fiwh6eSeRK7zwIKG2MA8i3rV/DGa3tdttQGgWyatG/SkncT53KHQaS5Jh9MNOT3dmFL0FjTY08And/Cw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="assets/styles/animate.css">

</head>

<body class="main-body">
    <section class="privicy_sec">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2 class="text-green">POLÍTICA DE PRIVACIDAD</h2>
                </div>
                <div class="col-lg-12">
                    <p>
                        <meta charset="utf-8"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"></strong>
                    </p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Si estás aquí es porque quieres saber más sobre las obligaciones y derechos que te corresponden como usuario de esta web </span><span style="font-size:1pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">www.wabisabicamperiza.com</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> y eso está muy bien. Nuestro deber es informarte y el tuyo estar debidamente informado.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">En esta Política de Privacidad te informaremos con total transparencia sobre la finalidad de este sitio web y todo lo que afecta a los datos que nos facilites, así como de las obligaciones y derechos que te corresponden.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Para empezar, debes saber que este sitio web se adapta a la normativa vigente en relación con la protección de datos, lo que afecta a los datos personales que nos facilites con tu consentimiento expreso y a las cookies que utilizamos para que este sitio web funcione correctamente y pueda desarrollar su actividad.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">Concretamente, esta web se ajusta al cumplimiento de las siguientes normativas:</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">El </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">RGPD </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">(</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo de 27 de abril de 2016 relativo a la protección de las personas físicas</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">) que es la nueva normativa de la Unión Europea que unifica la regulación del tratamiento de los datos personales en los distintos países de la UE.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">La </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LOPD</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> (</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> y </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Real Decreto 1720/2007, de 21 de diciembre, el Reglamento de desarrollo de la LOPD</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">) que regula el tratamiento de los datos personales y las obligaciones que debemos asumir los responsables de una web o un blog a la hora de gestionar esta información.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre-wrap;">La </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">LSSI</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> (</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">) que regula las transacciones económicas mediante medios electrónicos, como es el caso de este blog.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75">&nbsp;</strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">DATOS DE IDENTIFICACIÓN</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">El responsable y titular de este sitio web es </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">WABI SABI</span></strong></p>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Nombre:</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> Guillermo Torres</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">NIF:</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;70257731E</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Domicilio Social:</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> C/Hilarion Eslava, 5 - 2A / CP 28015</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Actividad del sitio web</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">: Distribución de contenido relacionado con furgonetas camper, autocaravanas, muestra de publicidad, recomendación de productos de afiliado, venta de libros, venta de cursos y plataforma de venta de contenidos relacionados con la construcción de furgonetas camper.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Correo electrónico</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">: wabisabicamperiza@gmail.com</span></strong></p>
                        </li>
                    </ul>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Los datos que nos facilites con tu consentimiento, y de acuerdo al uso establecido en esta Política de Privacidad, serán incorporados a un fichero automatizado debidamente inscrito en la Agencia Española de Protección de Datos, en el que el responsable de dicho fichero es: WABI SABI. Esto quiere decir que tus datos están seguros, de acuerdo a lo que establece la ley.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Los datos personales que nos facilites, siempre con tu consentimiento expreso, se almacenarán y tratarán con los fines previstos y descritos a continuación en esta Política de Privacidad, hasta el momento en que nos pidas que los eliminemos</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Te informamos de que esta Política de Privacidad puede ser modificada en cualquier momento, con el fin de adaptarla a novedades legislativas o cambios en nuestras actividades, siendo vigente la que en cada momento se encuentre publicada en la web.&nbsp;</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Dicha modificación se te notificará antes de su aplicación.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75">&nbsp;</strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">CONDICIONES DE USO</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Debes saber, para tu tranquilidad, que siempre te solicitaremos tu consentimiento expreso para recabar tus datos con la correspondiente finalidad especificada en cada caso, lo que implica que, en caso de otorgar ese consentimiento, has leído y aceptado esta Política de Privacidad</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En el momento en que accedas y utilices esta web, asumes tu condición de usuario con tus correspondientes derechos y obligaciones.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Si eres mayor de 13 años, podrás registrarte como usuario en este sitio web sin el previo consentimiento de tus padres o tutores.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Si eres menor de 13 años, necesitarás el consentimiento de tus padres o tutores para el tratamiento de tus datos personales.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75">&nbsp;</strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">REGISTRO Y FINALIDAD DE TUS DATOS</span></strong></p>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">¿Con qué Finalidades Trata Tu Información Personal wabisabicamperiza.com?</span></strong></h2>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Tratamos tu información personal para operar, prestar y mejorar wabisabicamperiza.com y los servicios que ofrecemos a nuestros clientes. Entre estas finalidades se incluyen:</span></strong></p>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:16pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Compra y entrega de productos y servicios. Utilizamos tu información personal para facilitar la gestión de pagos y comunicarnos contigo en relación con pedidos, productos, servicios y ofertas promocionales.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Prestación, resolución de problemas y mejora de wabisabicamperiza.com&nbsp;</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Utilizamos tu información personal para aportar funcionalidad, analizar el rendimiento, resolver errores y mejorar la usabilidad y efectividad de wabisabicamperiza.com</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Recomendaciones y personalización. Utilizamos tu información personal para recomendar funcionalidades, productos y servicios que puedan interesarte, identificar tus preferencias y personalizar tu experiencia con wabisabicamperiza.com.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Cumplimiento de obligaciones legales. En algunos casos, tenemos la obligación legal de recabar y tratar tu información personal. Por ejemplo, recabamos información de vendedores sobre el lugar de establecimiento y la cuenta bancaria para verificar su identidad, entre otras finalidades.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Comunicarnos contigo. Utilizamos tu información personal para comunicarnos contigo en relación con wabisabicamperiza.com y los servicios que ofrecemos a través de diferentes canales (por ejemplo, por teléfono y correo electrónico).</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Publicidad. Utilizamos tu información personal para mostrar anuncios basados en tus intereses relacionados con funcionalidades, productos y servicios que puedan interesarte. Para más información, consulta la sección </span><a href="https://www.iberlibro.com/docs/legal/privacypolicy.shtml?cm_sp=Ftr-_-Page-_-about4#section7" style="text-decoration:none;"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Publicidad Basada en los Intereses del Usuario</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Prevención del Fraude y Riesgos Crediticios. Tratamos información personal para prevenir y detectar el fraude y el abuso con el fin de proteger la seguridad de nuestros clientes, de vendedores, wabisabicamperiza.com, y otros. También podemos utilizar métodos de calificación para evaluar y gestionar los riesgos crediticios.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:20pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Finalidades para las que recabamos tu consentimiento. También podemos solicitar tu consentimiento para tratar tu información personal con una finalidad concreta que te comunicaremos. Cuando prestes tu consentimiento para que tratemos tu información personal para una finalidad determinada, podrás revocarlo en cualquier momento y dejaremos de tratar tu información con esa finalidad.</span></strong></p>
                        </li>
                    </ul>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En función del formulario o sección a la que accedas, te solicitaremos exclusivamente los datos necesarios con las finalidades descritas a continuación. En todo momento, deberás dar tu consentimiento expreso, cuando te solicitemos información personal con las siguientes finalidades:</span></strong></p>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Las finalidades concretas que particularmente se indiquen en cada una de las páginas o secciones donde aparezca el formulario de registro o contacto electrónico.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Con carácter general, para atender tus solicitudes, comentarios, consultas o cualquier tipo de petición que realices como usuario a través de cualquiera de las formas de contacto que ponemos a tu disposición</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Para informarte sobre consultas, peticiones, actividades, productos, novedades y/o servicios; vía e-mail, fax, Whatsapp, Calendly, Skype, teléfono proporcionado, sms y mms.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Para enviarte comunicaciones comerciales o publicitarias a través de cualquier otro medio electrónico o físico, que posibilite realizar comunicaciones.</span></strong></p>
                        </li>
                    </ul>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La información relativa a nuestros clientes es una parte fundamental de nuestro negocio y no participamos en actividades de venta de la información personal de nuestros clientes a terceros. Wabi Sabi sólo comparte la información personal de sus clientes del modo descrito a continuación, con nuestros afiliados,. y con sus filiales que o bien estén sujetas al presente Aviso de privacidad o sigan prácticas al menos tan protectoras como las descritas en este Aviso de privacidad.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Estas comunicaciones, siempre serán relacionadas con nuestros productos, servicios, novedades o promociones, así como aquellos productos o servicios que podamos considerar de tu interés y que puedan ofrecer colaboradores, empresas o “partners” con los que mantengamos acuerdos de promoción o colaboración comercial.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">De ser así, te garantizamos que estos terceros nunca tendrán acceso a tus datos personales, con las excepciones reflejadas a continuación, siendo en todo caso estas comunicaciones realizadas por parte de </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">WABI SABI, como titular de la web.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Este sitio web muestra productos de afiliado de terceros. Concretamente de </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">AMAZON</span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Esto quiere decir que al hacer clic en “Comprar Ahora”, ‘’Comprar’’,&nbsp; o similar, se te redirigirá a la página donde se ofertan los productos.&nbsp;</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">En este caso, debes saber que únicamente proporcionamos y facilitamos los enlaces a las páginas y/o plataformas de estos terceros donde pueden adquirirse los productos que mostramos, en aras a facilitar la búsqueda y fácil adquisición de los mismos.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Estas páginas enlazadas y pertenecientes a terceros no han sido revisadas ni son objeto de controles, ni recomendación por nuestra parte, por lo que en ningún caso </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">WABI SABI </span><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">será considerada responsable de los contenidos de estos sitios web, de las responsabilidades derivadas de su uso en todos los ámbitos, ni por las medidas que se adopten relativas a la privacidad del usuario, tratamiento de sus datos de carácter personal u otras que pudieran establecerse.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 18pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Por todo ello, te recomendamos la lectura detenida y anticipada de todas las condiciones de uso, condiciones de compra, políticas de privacidad, avisos legales y/o similares de estos sitios enlazados antes de proceder a la adquisición de estos productos o uso de las webs.</span></strong></p>
                    <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:18pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75">&nbsp;</strong></p>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">¿Qué Información Personal de Clientes Recaba WABI SABI?</span></strong></h2>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">La información que recabamos de los clientes nos ayuda a prestar y mejorar de forma continua nuestros productos y servicios.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Estos son los tipos de información que recabamos:</span></strong></p>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:16pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Información que nos Facilitas: recibimos y almacenamos toda la información que nos facilitas a través de nuestra página web o de cualquier otro modo. Haz clic </span><a href="https://www.iberlibro.com/docs/legal/privacypolicy.shtml?cm_sp=Ftr-_-Page-_-about4#section12" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">aquí</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> para ver ejemplos de información que recopilamos. Puedes elegir no facilitar cierta información, pero si lo haces, no podrás disfrutar de muchos de nuestros servicios.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Información Automática: cada vez que interactúas con nosotros, recibimos y almacenamos de forma automática ciertos tipos de información, tales como información sobre tu uso, incluyendo tu interacción con el contenido y los servicios disponibles a través de nuestra página web. Al igual que hacen muchas otras páginas web, utilizamos "cookies" y otros identificadores únicos para recabar cierta información cuando tu navegador de Internet accede a wabisabicamperiza.com y a otro contenido ofrecido por o en nombre de wabisabicamperiza.com en otras páginas web. Haz clic </span><a href="https://www.iberlibro.com/docs/legal/privacypolicy.shtml?cm_sp=Ftr-_-Page-_-about4#section12" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">aquí</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> para ver ejemplos de información que recopilamos.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:20pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Información Procedente de Otras Fuentes: es posible que recibamos información sobre ti de otras fuentes.&nbsp;</span></strong></p>
                        </li>
                    </ul>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">¿Comparte wabisabicamperiza.com tu Información Personal?</span></strong></h2>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:16pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Comprar y Vender en Wabi Sabi: si compras o vendes artículos en la web de Wabi Sabi, enviaremos tus datos personales al socio contractual correspondiente (vendedor o comprador) con el fin de formalizar el contrato. En caso de vender artículos a través de empresas asociadas (incluidas aquellas que no están bajo el control de Wabi Sabi), en algunos casos particulares será necesario que enviemos tus datos personales a esas empresas para proceder a la venta de tus artículos.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Terceros Proveedores de Servicios: contratamos a otras sociedades y personas para realizar ciertas funciones en nuestro nombre. Algunas de las funciones que realizan son: enviar correos electrónicos, eliminar información repetida de las listas de clientes, realizar análisis de datos, ofrecer asistencia de marketing, gestionar pagos de tarjeta de crédito y ofrecer servicio de atención al cliente. Estos terceros proveedores de servicios tendrán acceso a la información personal necesaria para realizar sus funciones, pero no podrán utilizarla para otros fines. Además, deberán tratar la información personal de conformidad con el presente Aviso de privacidad y la legislación aplicable en materia de protección de datos.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ofertas promocionales: en ciertos casos enviaremos ofertas en nombre de otras empresas a algunos clientes seleccionados de Wabi Sabi. En estos casos, no facilitaremos tu nombre ni tu dirección.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Transmisiones de Sociedades: a medida que desarrollamos nuestro negocio, podemos comprar o vender otras sociedades o servicios. En dichas transacciones, uno de los activos de las sociedades transferidas suele ser la información personal de los clientes; dicha información estará en todo caso sujeta a los compromisos adquiridos en los Avisos de privacidad preexistentes (a menos, claro está, que el cliente lo autorice de otro modo). Por supuesto, en el caso de que Wabi Sabi o la mayor parte de sus activos sean adquiridos por un tercero, la información personal de los clientes sería uno de los activos transferidos. En dicho caso, tu información personal está sujeta a este Aviso de privacidad y la ley de protección de datos correspondiente.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:20pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Protección de Wabi Sabi y Otros: divulgamos información personal y datos de cuentas de nuestros clientes cuando creemos que su divulgación es necesaria para el cumplimiento de la ley, para hacer cumplir o aplicar las Condiciones Generales de Uso y otros acuerdos o para proteger los derechos, la propiedad, o seguridad de WabiSabiCamperiza.com, nuestros usuarios, o terceros. Lo anterior incluye el intercambio de información con otras sociedades y organizaciones para la protección contra el fraude y la reducción del riesgo de crédito.</span></strong></p>
                        </li>
                    </ul>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Transferencias fuera del Espacio Económico Europeo. Siempre que transmitimos información personal a países situados fuera del Espacio Económico Europeo, nos aseguraremos de que la información es transferida de acuerdo con este Aviso de privacidad y conforme a lo permitido por las leyes aplicables en materia de protección de datos.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Aparte de lo establecido anteriormente, se te informará en el caso de que cualquier información sobre ti se comparte con terceras partes, al objeto de que tengas la oportunidad de elegir que no se comparta tu información.</span></strong></p>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">¿Está a salvo mi información personal?</span></strong></h2>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Diseñamos nuestros sistemas y dispositivos teniendo en cuenta tu seguridad y privacidad.</span></strong></p>
                    <ul style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:16pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Trabajamos para proteger la seguridad de tu información personal durante la transmisión utilizando Secure Sockets Layer software (SSL), que codifica la información que introduces.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Al gestionar datos de tarjetas de crédito, cumplimos los Estándares de Seguridad de los Datos de la Industria de las Tarjetas de Pago con la plataforma de pagos Stripe.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Contamos con sistemas de seguridad físicos, electrónicos y procedimentales en relación con la recogida, almacenamiento, y divulgación de información personal del cliente. Nuestros procedimientos de seguridad implican que en ocasiones podamos solicitarle pruebas de identidad antes de facilitarte información personal.</span></strong></p>
                        </li>
                        <li dir="ltr" style="list-style-type:disc;font-size:13.5pt;font-family:Arial;color:#111111;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;" aria-level="1">
                            <p dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:0pt;margin-bottom:20pt;" role="presentation"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Es importante que te protejas contra el acceso no autorizado de terceros a tu contraseña y a tu ordenador. Comprueba que cierras tu sesión al acabar siempre que estés utilizando un ordenador compartido.</span></strong></p>
                        </li>
                    </ul>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Publicidad Basada en los Intereses del Usuario</span></strong></h2>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Wabi Sabi es un mercado en línea. Podremos trabajar con anunciantes o anunciantes afiliados para mostrarte publicidad basada en los intereses del usuario en otras páginas web, usando la información que pones a nuestra disposición cuando accedes a Wabi Sabi. La publicidad basada en los intereses del usuario, en ocasiones denominado también anuncios personalizados o dirigidos, se genera y se te muestra a partir de la información recogida de actividades tales como la compra en nuestros sitios web, o la visita de sitios web que incluyen contenido o anuncios de Wabi Sabi.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">No facilitamos ninguna información personal ni a anunciantes ni a sitios web de terceros. Dichas empresas utilizan a veces recursos técnicos para enviar directamente a tu navegador los anuncios que aparecen en nuestros sitios web. Cuando esto ocurre, automáticamente reciben tu dirección IP. También pueden utilizar cookies, JavaScript, web beacons (también conocidos como etiquetas de acción o gifs de un píxel), y otras herramientas, para medir la eficacia de sus anuncios y personalizar el contenido de los mismos. Para obtener información acerca de cómo controlar y eliminar las cookies (incluyendo cookies de terceros), </span><a href="https://www.iberlibro.com/docs/Legal/aviso-de-cookies.shtml" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">lea nuestro Aviso de cookies</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Actualmente, utilizamos píxeles de terceras empresas, extensiones de navegador y cookies de anunciantes afiliados incluyendo, pero no limitado a Facebook, Google y Amazón. Si tienes alguna pregunta sobre sus avisos de privacidad, te sugerimos ponerte en contacto con ellos.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:0pt;padding:0pt 0pt 13pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Si deseas dejar de recibir estos anuncios basados en los intereses del usuario de terceras empresas publicitarias de la NAI. (</span><a href="http://optout.networkadvertising.org/#!/" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Network Advertising Initiative</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">) o empresas bajo la DAA (</span><a href="http://optout.aboutads.info/#!/" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Digital Advertising Alliance?s Self-Regulatory Principles for Online Behavioral Advertising</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">), puedes hacerlo a partir de las páginas de la NAI o DAA.</span></strong></p>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:0pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75">&nbsp;</strong></p>
                    <h2 dir="ltr" style="line-height:1;background-color:#ffffff;margin-top:13pt;margin-bottom:0pt;padding:0pt 0pt 3pt 0pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:15pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">¿A qué información tengo acceso?</span></strong></h2>
                    <p dir="ltr" style="line-height:1.74;background-color:#ffffff;margin-top:13pt;margin-bottom:13pt;"><strong style="font-weight:normal;" id="docs-internal-guid-f77e338c-7fff-5364-fe20-028852b6fb75"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Puedes acceder a tus datos, incluyendo tu nombre, dirección, direcciones de envío, opciones de pago, datos de perfil, e historial de compra en el apartado "Mi cuenta" de la página web. </span><a href="https://www.iberlibro.com/docs/legal/privacypolicy.shtml?cm_sp=Ftr-_-Page-_-about4#section11" style="text-decoration:none;"><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Aquí</span></a><span style="font-size:13pt;font-family:Roboto,sans-serif;color:#333333;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> puedes ver una lista de ejemplos de datos a los que tienes acceso.
                            </span></strong></p>
                </div>
            </div>
        </div>
    </section>






    <!-- custom js -->
    <script src="assets/scripts/jquery.min.js"></script>
    <script src="assets/scripts/bootstrap.min.js"></script>
    <script src="assets/scripts/slick.js"></script>
    <script src="assets/scripts/slick-animation.min.js"></script>
    <script src="assets/scripts/owl.carousel.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js" integrity="sha512-IsNh5E3eYy3tr/JiX2Yx4vsCujtkhwl7SLqgnwLNgf04Hrt9BT9SXlLlZlWx+OK4ndzAoALhsMNcCmkggjZB1w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="assets/scripts/fancybox.min.js"></script>
    <script src="assets/scripts/jquery.matchHeight-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TimelineMax.min.js" integrity="sha512-ExEP0u1SOp7gvzBoHWYmi6CEzdW2VHgfMeRZTetgX4HazJhC/UO1l83VGn4TLvgmIAxotN8uBcDE05a3sJglOA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.2/TweenMax.min.js" integrity="sha512-O+atZ/gABlcFlpIoLQR04f72qHqZWKwTVsQZHqk/8VE2nrzDlnqhXbnXP7Gh/TyhpPT8tEUm5A580GG8AloHTA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/ScrollMagic.min.js" integrity="sha512-kDuUo39RGApdfHkM1WQL8Pg9BYtYGS5rD14AzePsD4SEaixw7v/ykAkLMdsSjuBCNFE6/FAP+WIHh6N6QZJl5w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/plugins/animation.gsap.js" integrity="sha512-b3ujtnGapNU4CVHnbzXMfHFoTkrZE3D39PT6iGLsHm9MLG5VP57ZGKIsUI+zD88rf91APZ79m6t75WAJYnNobQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="assets/scripts/main.js"></script>


</body>

</html>